[package]
name = "usdcpp"
version = "0.1.0"
authors = ["Luke Titley <from+usd_rs@luketitley.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
