[package]
name = "usd-rs"
version = "0.1.0"
authors = ["Luke Titley <luke@titley.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usdcpp = {path="../usd-cpp"} # We need this for the libs to link against
cpp = "0.5"

[build-dependencies]
usdcpp = {path="../usd-cpp"} # We need this for the headers
cpp_build = "0.5"
